In [4]:
import numpy as np

In [5]:
my_list = [10,20,30,40]

In [6]:
my_numpy_array = np.array(my_list)

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
my_numpy_array.max()

np.int64(40)

In [9]:
my_numpy_array.min()

np.int64(10)

In [10]:
my_numpy_array.sum()

np.int64(100)

In [11]:
# array arithmetic

In [12]:
my_numpy_array1 = np.array([1,2])
my_numpy_array2 = np.array([2,3])

In [13]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [14]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [15]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [16]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [17]:
# arrange & indexing

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np_array = np.arange(0,10)

In [20]:
np_array[1:4:]

array([1, 2, 3])

In [21]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
np_array[2:6:2]

array([2, 4])

In [23]:
# random

In [24]:
np.random.randn(4,4)

array([[ 0.3099594 , -0.33134921,  0.73969285,  0.34131017],
       [ 0.67954904,  1.62136351, -0.80632716, -0.20832307],
       [-1.46468237,  1.24726553, -1.12466617,  0.42467437],
       [-0.60603807,  0.03004188, -1.26203703, -1.40605451]])

In [25]:
np.random.randint(1,300,5)

array([287,  28, 264, 239, 100], dtype=int32)

In [ ]:
# matrix

In [27]:
numpy_matrix = np.array([[5,10],[15,20]])

In [28]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [29]:
numpy_matrix[1][1]

np.int64(20)

In [30]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# matrix arithmetic

In [34]:
first_matrix = np.array([[10,20],[30,40]])
second_matrix = np.array([[5,15],[25,35]])

In [35]:
first_matrix + second_matrix

array([[15, 35],
       [55, 75]])

In [36]:
first_matrix - second_matrix

array([[5, 5],
       [5, 5]])

In [37]:
first_matrix / second_matrix

array([[2.        , 1.33333333],
       [1.2       , 1.14285714]])

In [38]:
third_matrix = np.array([[20,60]])

In [39]:
first_matrix + third_matrix

array([[ 30,  80],
       [ 50, 100]])

In [40]:
third_matrix.shape

(1, 2)

In [41]:
# dot product

In [42]:
first_matrix = np.array([[10,20,30]])

In [43]:
first_matrix.shape

(1, 3)

In [44]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [45]:
second_matrix.shape

(3, 2)

In [46]:
result_matrix = first_matrix.dot(second_matrix)

In [47]:
result_matrix

array([[120, 180]])

In [48]:
result_matrix.shape

(1, 2)

In [49]:
# transpose & reshape

In [50]:
matrix_array = np.array([[10,20],[20,30],[30,40]])
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [51]:
matrix_array.shape

(3, 2)

In [55]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [56]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [58]:
random_array = np.random.rand(6,1)
random_array

array([[0.16922971],
       [0.42787555],
       [0.7549485 ],
       [0.23223064],
       [0.70638177],
       [0.42217752]])

In [61]:
random_array.reshape(3,2)

array([[0.16922971, 0.42787555],
       [0.7549485 , 0.23223064],
       [0.70638177, 0.42217752]])

In [62]:
random_array.reshape(2,3)

array([[0.16922971, 0.42787555, 0.7549485 ],
       [0.23223064, 0.70638177, 0.42217752]])

In [63]:
# mean & std

In [64]:
data = np.array([12,10,13,15,18,25,100,108])
data

array([ 12,  10,  13,  15,  18,  25, 100, 108])

In [65]:
data.mean()

np.float64(37.625)

In [66]:
data.std()

np.float64(38.61002946126822)

In [67]:
# math equations
# 2x + 3y = 8 and 5x + 7y = 19

In [68]:
# coefficient
A = np.array([[2,3],[5,7]])

In [70]:
# constant
b = np.array([8,19])

In [71]:
solution = np.linalg.solve(A,b)
solution

array([1., 2.])