In [2]:
import numpy as np

In [3]:
my_list = [10,20,30,40]

In [5]:
my_numpy_array = np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [14]:
my_numpy_array.max()

np.int64(40)

In [21]:
my_numpy_array.min()

np.int64(10)

In [22]:
my_numpy_array.sum()

np.int64(100)

In [15]:
# array arithmetic

In [16]:
my_numpy_array1 = np.array([1,2])
my_numpy_array2 = np.array([2,3])

In [17]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [18]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [19]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [20]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [23]:
# arrange & indexing

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np_array = np.arange(0,10)

In [26]:
np_array[1:4:]

array([1, 2, 3])

In [27]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
np_array[2:6:2]

array([2, 4])

In [29]:
# random

In [32]:
np.random.randn(4,4)

array([[ 1.21636975,  1.20556467,  1.72009179,  0.90827423],
       [ 3.33108881, -0.88043182,  0.06653313,  0.8940507 ],
       [ 0.26908431, -0.66547212,  0.22422075, -0.38172099],
       [-1.07936527,  0.39785709, -1.57698254,  0.25985719]])

In [33]:
np.random.randint(1,300,5)

array([ 47, 225, 155, 230,  30], dtype=int32)